### ISSUE TITLE
Flashing  x270  with MECleaner modded firmware

### ISSUE THREAD

**Issue by leftishness** [je-nix/x270-internals#1]
Hey I noticed your thread from a while ago about using MEcleaner on your x270. I have an x270 and I'm looking into doing this but have never done this before. I just wanted to confirm your setup and steps on how you performed this on your x270 before I proceed. Any input would be appreciated.

**Comment by ghost** [comment]
I also have a x270 with a bricked BIOS. I was able to recover the corrupted BIOS .bin with a ch341a_spi programmer using flashrom. Now I'm completely lost on what to do.
Lenovo only offers an .iso through the webpage, and inside the contents it doesn't come with a BIOS .img.

Were you able to flash the BIOS correctly?

Chip is winbond 25Q128FV.
